---
apiVersion: cloudbees.com/v2026.3
kind: application
metadata:
  name: qe app 3
  description: GqMVTtBFxLlYwePNipDHFhnZBNqiKQDQSYpGRqmiUiSJiKjHgIDgrnBCOLxhSPacoYfESOqiQEgHCYABmLVgBLFqhlNbnrnboRCpAuejRCJhZnSsZMXWRsFwgjvrTHzfbWtvZwuCvMVLXLZAftojODWqeiSqVtriidzCDiLNzbOQDbflASIeOhOWmgpGqkOsGRWpuQLLypsJNUXwqcMigTkznwAlMrXiHhmoQtGHwGLmRoCGFRWCfmkdJoTJeyqbIFWxYctProqYwikNVJJJbprtcHDzGrLmUcGWkezgJXHMYxotkoBXqpaeiNpNUtncydUHNLWmicksPkDWBQqXKdxsnYMjQcoDIEIkyizSXEzMqSksERJPqclhSjimZDiUhyDEuAFTsRLlfIvfDHKBwOcFRPyjYFqIhvXmEjHAghUChvuceWplrBmyNDoBQxYWWn
spec:
  applicationType: external
