
application 'qe app 1', {
  description = 'GqMVTtBFxLlYwePNipDHFhnZBNqiKQDQSYpGRqmiUiSJiKjHgIDgrnBCOLxhSPacoYfESOqiQEgHCYABmLVgBLFqhlNbnrnboRCpAuejRCJhZnSsZMXWRsFwgjvrTHzfbWtvZwuCvMVLXLZAftojODWqeiSqVtriidzCDiLNzbOQDbflASIeOhOWmgpGqkOsGRWpuQLLypsJNUXwqcMigTkznwAlMrXiHhmoQtGHwGLmRoCGFRWCfmkdJoTJeyqbIFWxYctProqYwikNVJJJbprtcHDzGrLmUcGWkezgJXHMYxotkoBXqpaeiNpNUtncydUHNLWmicksPkDWBQqXKdxsnYMjQcoDIEIkyizSXEzMqSksERJPqclhSjimZDiUhyDEuAFTsRLlfIvfDHKBwOcFRPyjYFqIhvXmEjHAghUChvuceWplrBmyNDoBQxYWWn'
  applicationType = 'external'
}
