
application 'qe app 3', {
  description = 'GqMVTtBFxLlYwePNipDHFhnZBNqiKQDQSYpGRqmiUiSJiKjHgIDgrnBCOLxhSPacoYfESOqiQEgHCYABmLVgBLFqhlNbnrnboRCpAuejRCJhZnSsZMXWRsFwgjvrTHzfbWtvZwuCvMVLXLZAftojODWqeiSqVtriidzCDiLNzbOQDbflASIeOhOWmgpGqkOsGRWpuQLLypsJNUXwqcMigTkznwAlMrXiHhmoQtGHwGLmRoCGFRWCfmkdJoTJeyqbIFWxYctProqYwikNVJJJbprtcHDzGrLmUcGWkezgJXHMYxotkoBXqpaeiNpNUtncydUHNLWmicksPkDWBQqXKdxsnYMjQcoDIEIkyizSXEzMqSksERJPqclhSjimZDiUhyDEuAFTsRLlfIvfDHKBwOcFRPyjYFqIhvXmEjHAghUChvuceWplrBmyNDoBQxYWWn'
  applicationType = 'external'
}
