---
apiVersion: cloudbees.com/v2026.3
kind: workspace
metadata:
  name: qe workspaceApplyDslSyncTestsBeIWU
  description: Automation backend tests
spec:
  agentUnixPath: /tmp
  local: true
  workspaceDisabled: true
  zoneName: default
